[phases.setup]
nixPkgs = ["python", "google-chrome", "playwright-driver.browsers"]

[phases.install]
cmds = ["pip install -r requirements.txt", "PLAYWRIGHT_BROWSERS_PATH=/app/.cache playwright install chromium"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/.cache"
