# Generated by Django 5.2.13 on 2026-04-21 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_video_id', models.CharField(max_length=255)),
                ('comment_id', models.CharField(max_length=255, unique=True)),
                ('comment_text', models.TextField()),
                ('commenter_username', models.CharField(max_length=255)),
                ('suggested_reply', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_replied', models.BooleanField(default=False)),
                ('is_ignored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
